# Html5BoilerplateHelper will first check your ENV and
# then this yml file for these values. If they are both
# empty, the google code block will not be used.
#
# e.g. ENV['GOOGLE_ACCOUNT_ID'] || yml[:google_account_id]
# e.g. ENV['GOOGLE_API_KEY'] || yml[:google_api_key]
#
defaults: &defaults
  :google_account_id: 'UA-3202633-12'
  :google_api_key: 'ABQIAAAA9i9eJP3lvywadcKyDIwkERQNScEgd_s9KHpNzazMTy3hRJ6mgBQ33z-xXQ4slpbwMph5eBu67ClRFQ'

:development:
  <<: *defaults

:test:
  <<: *defaults

:staging:
  <<: *defaults

:production:
  <<: *defaults
